config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  root 'welcome#index'
  
  get '/course' => 'pages#course'
  get '/story' => 'pages#story'
  get '/work-with-me' => 'pages#hire'
  
  resources :posts do
    resources :comments
    resources :ratings
  end
  
  resources :categories

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :posts
  has_many :categories
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :post_categories
	has_many :posts, through: :post_categories
	validates_uniqueness_of :name

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  
  validates :name, :body, presence: true 
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, :use => :slugged
  belongs_to :admin
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :comments
  has_many :ratings
  has_attached_file :image, 
  :styles => {
      :thumb => "100x100#",
      :small  => "150x150>",
      :medium => "200x200" }

	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :title, :content, :categories, :slug, presence: true 


    
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  
   belongs_to :post 
   belongs_to :category
  
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :post
  
  validates :rating_number, presence: true 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  private
	def get_categories
		@categories = Category.all.order(:name)
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
     before_action :authenticate_admin!, except: [:index, :show]
   
     before_action :ensure_category_ownership, only: [:edit, :update, :destroy]
  

   def index
     @categories = Category.all.order(:name)
   end

   def show
     @category = Category.find(params[:id])
   end

   def new
     @category = current_admin.categories.build
   end

   def create
     
     @category = current_admin.categories.build(category_params)
     
     if @category.save
       redirect_to @category
     else
       render "new"
     end
   end
   

  private
  def category_params
    params.require(:category).permit(:name)
   end
  
  def ensure_category_ownership
    if current_admin != Category.find(params[:id]).admin
      redirect_to root_path, "You do not have access to do perform that action"
    end
  end

 end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
 
  before_action :set_post 
  
  def new
    @comment = Comment.new
  end
 
  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = @post.id
    
    if @comment.save
      redirect_to @post
    else
      render 'new'
    end 
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    @comment.update(comment_params)
  end
  
  def destroy
    @comment.destroy
    redirect_to root_path
  end
  
  private
    
    def set_comment
      @comment = Comment.find(params[:id])
    end
    
    def set_post
      @post = Post.friendly.find(params[:post_id])
    end
    
    def comment_params
      params.require(:comment).permit(:name, :body)
    end

  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def course
  end

  def story
  end
  
  def hire
  end
  
end

app/controllers/posts_controller.rb
 class PostsController < ApplicationController
  
     before_action :authenticate_admin!, except: [:index, :show]
   
     before_action :ensure_post_ownership, only: [:edit, :update, :destroy]

   def index
     @posts = Post.order(updated_at: :desc);
   end

   def show
     
     @post = Post.friendly.find(params[:id])


     @comments = Comment.where(post_id: @post.id).order("created_at DESC")
     
     
     @ratings = Rating.where(post_id: @post.id).order("created_at DESC")
    
    
    if @rating.blank?
      @avg_rating = 0 
    else
      @avg_rating = @ratings.average(:rating_number).round(2)
    end
     
  end
     
   def new
     @post = current_admin.posts.build
   end

   def create 
     @post = current_admin.posts.build(post_params)
     
     if @post.save
       redirect_to @post, notice: "Your post has been created!"
     else
       render "new"
     end    
   end
   
 	def edit
    @post = Post.friendly.find(params[:id])
	end

	def update
    @post = Post.friendly.find(params[:id])

    if @post.update(params[:post].permit(:title, :content, :image, :category_ids => []))
			redirect_to @post
		else
			render 'edit'
		end
	end
   
	def destroy
    @post = Post.friendly.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end
   
   
  private
   
   def post_params
     params.require(:post).permit(:title, :content, :image, :rating, :category_ids => [])
   end

  def ensure_post_ownership
    if current_admin != Post.friendly.find(params[:id]).admin
      redirect_to root_path, "You do not have access to do perform that action"
    end
  end
  
    
 end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  
  before_action :set_rating, only: [:show, :edit, :update, :destroy]
 
  before_action :set_post  
  
  def new
    @rating = Rating.new
  end
  
  def edit
  end
 
  def create
    @rating = Rating.new(rating_params)
    @rating.post_id = @post.id
    
    if @rating.save
      redirect_to @post
    else
      render 'new'
    end 
  end
  

  
  def update
    @rating.update(rating_params)
  end
  
  def destroy
    @rating.destroy
    redirect_to root_path
  end
  
  private
    
    def set_rating
      @rating = Rating.find(params[:id])
    end
    
    def set_post
      @post = Post.find(params[:post_id])
    end
    
    def rating_params
      params.require(:rating).permit(:rating_number)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.order(updated_at: :desc).limit(3)
    
    @post = Post.all.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_categories.html.erb
<ul>
  <% category.posts.order(:title).uniq.each do |post| %>

  <h4 class="similar_posts">
    <%= link_to post.title, post %>
  </h4>
  <% end %>
</ul>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
 <div class="control-group">
   <%= f.label :name %>
   <div class="controls">
     <%= f.text_field :name %>
   </div>
 </div>

 <div class="form-actions">
   <%= f.submit nil %>
   <%= link_to 'Cancel', categories_path %>
 </div>
<% end %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<h3>Click on any link below to see articles tagged with the category</h3>
<ul>
	<% @categories.each do |category| %>
		<h4>
	  	<%= link_to category.name, category %>
	  </h4>
	<% end %>
</ul>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58060808-3', 'auto');
  ga('send', 'pageview');

</script>

app/views/categories/new.html.erb
<h1>New Category</h1>
<% if @category.errors.any? %>
<div class="error_messages">
   <h2>You're missing some fields</h2>
   <ul>
     <% @category.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
   </ul>
 </div>
<% end %>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<h2 class="heading"><%= @category.name %> Posts</h2>
<h3 class="idea">There are <%= @category.posts.count %> posts filed under <%= @category.name %></h3>
<ul>
	<% @category.posts.order(:title).each do |post| %> <br />
		<h1 class="course">
      <%= image_tag post.image.url(:thumb) %> 
	  	<%= link_to post.title, post %>
	  </h1>
	<% end %>
</ul>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<%= f.label :name %><br>
	<%= f.text_field :name %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_area :body %><br>
	<br>
	<%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_path(@post) %>

app/views/comments/new.html.erb
<h1> New comment </h1>

<%= render 'form' %>

<%= link_to 'Back', post_path(@post) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Happy, Healthy & Wealthy</title>
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"      type="text/javascript"></script>
<![endif]-->
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
<%= metamagic title: "Happy, Healthy & Wealthy", description: "A blog about finding happiness, health, and wealth", keywords: %w(personal finance happy health wealth) %>
<link href='http://fonts.googleapis.com/css?family=Bitter' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Comfortaa:400,300,700' rel='stylesheet' type='text/css'>

<meta name="viewport" content="width=device-width, initial-scale=1.0">

   <%= analytics_init if Rails.env.production? %>
  
</head>
<body>
  

  

<div class='navbar navbar-default navbar-fixed-top'>
  <div class='container'>
    <div class='navbar-header'>
      <a href='/' class='navbar-brand'> <%= image_tag("happyhealthywealthy_transparent.png", :alt => "HappyHealthyWealthy", :class => "img-logo") %></a>

        <button type="button" class='navbar-toggle collapsed' data-toggle='collapse' data-target='.navbar-collapse'>
          <span class='sr-only'>Toggle Navigation</span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
    </div>
    
      <ul class='nav navbar-nav navbar-right collapse navbar-collapse'>
        <% if admin_signed_in? %>
            <li><%= link_to "Sign Out", destroy_admin_session_path, method: :delete %></li>
            <li><a href="/posts">Blog</a></li>
            <li><a href="/course">Free Mini-Course</a></li>
            <li><a href="/story">My Story</a></li>
        <% else %>
            <li><a href="/posts">Blog</a></li>
            <li><a href="/course">Free Mini-Course</a></li>
            <li><a href="/work-with-me">1:1 Help</a></li>
            <li><a href="/story">My Story</a></li>
        <% end %>
      </ul>
    
    
  </div>
</div>


<%= yield %>
  
  <footer class="blog-footer">
    <p>This site was developed using Ruby on Rails & Bootstrap by <a class="footer_bottom" href="https://twitter.com/jkent2910">me, myself & I</a>.</p>
    <p>
      <a class="footer_bottom" href="#">Back to top</a>
    </p>
  </footer>
</body>

app/views/pages/course.html.erb
<div class="container">
  <div class="row">
    <div class="visible-md visible-lg col-md-12 col-lg-12">
      <%= image_tag("course_banner.png", :alt => "Course Banner", :class => "course_banner") %>
    </div>
    
    <div class="small_screen">
    <div class="visible-sm visible-xs col-sm-12 col-xs-12">
      <%= image_tag("course-banner-small.png", :alt => "Course Banner", :class => "course_banner") %>
    </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-lg-12">
      <h1 class="course">Develop a </h1> <h1 id="strong"> personal financial strategy </h1> <h1 class="course">that you can believe in; Understand how to </h1><h1 id="strong">  increase your financial position </h1>; <h1 id="strong"> Stop worrying </h1> <h1 class="course">about money; </h1><h1 id="strong">  Feel confident in your future </h1> 
    </div>
  </div>  
<br /><br />
  
  <div class="row">
    <div class="col-md-12 col-lg-12">
      <h1 id="strong">Week 1: Get in the right mindset </h1><h1 class="course"> - in order to make drastic changes, you must have the right motivation.  The first week of the course focuses on identifying what has held you back in the past, drives you to identify specific and tangible goals for the next 5 weeks, and provides you the resources you need to take the first step!"</h1><br />
      <h1 id="strong">Week 2: Establishing a baseline</h1><h1 class="course"> - the second week, we jump right in!  I work with you to understand your current situation in real terms - net worth and monthly income vs. expenses.</h1><br />
      <h1 id="strong">Week 3: Developing a budget that you can sustain</h1><h1 class="course"> - now that you understand how much you have coming in vs. going out, I work with you to develop a personalized budget that makes sense for you.</h1><br />      
      <h1 id="strong">Week 4: Insurance & Extra ways to save - </h1><h1 class="course">Even when you don't think there is any extra money, it's likely that you can find some hiding somewhere.  This week we focus on making sure you have the right insurance in place and then learn little tips and tricks to save money you didn't even realize you had! We also discuss long-term/retirement savings and how to accurately assess your needs in retirement.</h1><br />      
      <h1 id="strong">Week 5: Reflection, Congratulations, and Next Steps -</h1><h1 class="course"> You've made it!!  We wrap up with some reflection and take time to realize and be proud of how much we've accomplished these past five weeks.  But, the journey doesn't stop here!  At the end of the course, I provide you ongoing resources to utilize as you continue on your path towards financial independence!</h1><br />      
    </div>
  </div>
  
<div class="row">
  <div class="col-md-12 col-lg-12">
    <h3 class="main_subheader">
      Yes, all of this is 100% FREE!  What do you have to lose?  
    </h3>
  </div>
  </div>
  
<div class="row">
  <div class="col-md-12 col-lg-12">
<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{
    background:#fff; 
    clear:left; 
    font:14px Helvetica,Arial,sans-serif; 
  }
  
  #mc_embed_signup label { 
    text-align: center;
  }
  
    #mc_embed_signup input.button {
      margin: 0 auto;
      
    }
  
  #mc_embed_signup input.email {
    margin: 0 auto;
    margin-bottom: 10px;
  }
	/* Addyour own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//happyhealthywealthy.us10.list-manage.com/subscribe/post?u=f99a8de8f49f7e3b52c765fec&amp;id=8c5a26c286" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<label for="mce-EMAIL">FREE 5-Week Mini-Course Sign-up!  No obligation - opt out at any time!</label>
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_f99a8de8f49f7e3b52c765fec_8c5a26c286" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
  </div>
  </div>
</div>

app/views/pages/hire.html.erb
<div class="container">
  <div class="row">
    <div class="visible-md visible-lg col-md-12 col-lg-12">
      <%= image_tag("work.png", :alt => "Work Banner", :class => "course_banner") %>
    </div>
    
    <div class="small_screen">
    <div class="visible-sm visible-xs col-sm-12 col-xs-12">
      <%= image_tag("hire_small.png", :alt => "Work Banner", :class => "course_banner") %>
    </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-lg-12">
      <h1 class="course">Interested in personalized strategies?</h1>
    </div>
  </div>
  
    <div class="row">
    <div class="col-md-12 col-lg-12">
      <h1 class="course"><a href="https://docs.google.com/forms/d/1KKqIYTESpxapMhBG6kykEetk42XYujsAdTcb-xe82TM/viewform?usp=send_form">Complete this application to work with me</a></h1>
    </div>
  </div>
      
   <div class="row">
    <div class="col-md-12 col-lg-12">
      <h1 class="course">I am only available to work 1:1 with a limited number of clients, and I ask that everyone who is interested fill out the above application to ensure that we are a good fit for each other.</h1>
    </div>
  </div>
  
   <div class="row">
    <div class="col-md-12 col-lg-12">
      <h1 class="course">If you're worried or wondering about cost, I work out future payment plans for each client.  I do not take any money up-front as this would be counter-productive!</h1>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-12 col-lg-12">
      <h1 class="course">If you have any questions, <a href="mailto: jkent2910@gmail.com">E-mail me</a></h1>
    </div>
  </div>

app/views/posts/_form.html.erb
<%= simple_form_for @post, :html => {:multipart => true} do |f| %>
<% if @post.errors.any? %>
<div class="errors">
  <p><% @post.errors.count %> prevented post from saving </p>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<%end%>

<div class="container">
  <%= f.input :title, input_html: {class:'form-control'} %>
  <%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>
  <%= tinymce %>
  <%= f.input :image, input_html: {class: 'form-control'} %>
   <%= f.label 'File under at least one category' %>
   <% Category.all.order(name: :asc).each do |category| %>
     <div>
       <%= check_box_tag "post[category_ids][]", category.id %>
       <%= category.name %>
     </div>
   <% end %>
  <%= f.button :submit, class: "btn btn-primary" %>
  
</div><!--- container --->

<% end %>

app/views/posts/edit.html.erb
	<h1>Edit Post</h1>

	<%= render 'form' %>

app/views/posts/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-xs-12 col-md-8 col-md-offset-2">
      <div class="small_screen">
      <h2 class="heading">Welcome to my blog!</h2>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-xs-12 col-md-8 col-md-offset-2">
   
      <h3 class="idea"> Have an idea for a post?  <a href="mailto:jkent2910@gmail.com>">E-mail me!</a> </h3>
   
    </div>
  </div>
  <% @posts.each_slice(3).each do |posts| %>
  <div class="row">
      <% posts.each do |post| %>
      <div class="col-md-4 col-lg-4">
        <div class="post">
          <div class="img_wrapper">
            <%= link_to post do %>
            <%= image_tag post.image.url(:medium), :class => "blog_img" %> 
            <% end %>
          </div> <!--- image wrapper ---->
            <h2> <%= link_to post.title, post %> </h2>
                <h4>
                Tag: <%= post.categories.map { |category| link_to category.name, category_path(category.id)}.join(', ').html_safe %> 
                </h4>
        </div> <!---- post ----->
      </div> <!---- col-md-4 ---->
            <% end %>

  </div> <!----- row ---->
<% end %>
</div> <!----- container-fluid ----->

app/views/posts/new.html.erb
<h1>Write and Publish a New Post</h1>
<% if @post.errors.any? %>
<div class="error_messages">
   <h2>You're missing some fields</h2>
   <ul>
     <% @post.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
   </ul>
 </div>
<% end %>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
 <%= tinymce %>

<div class="container">
  <div class="row">
    <div class="col-md-12 col-lg-12">
      <div class="small_screen">
      <h3 class="main_posts">
        <%= @post.title %>
      </h3>
      </div>
    </div>
    <div class="row">
    <div class="col-md-12 col-lg-12">
      <h3 class="idea">
        <%= @post.created_at.strftime('%b %d, %Y') %>
      </h3>
    </div>
    </div>
  </div>
  
  <div class='row'>
    <div class="col-md-4-offset-6 col-lg-4-offset-6 text-center">
      <%= image_tag @post.image.url(:medium) %>
    </div>
  </div> 
  <div class="row">
    <div class="col-md-4-offset-6 col-lg-4-offset-6 text-center">
    <h4 class="comment_header">
      Tag: <%= @post.categories.map { |category| link_to category.name, category_path(category.id)}.join(', ').html_safe %> 
    </h4>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-4-offset-6 col-lg-4-offset-6 text-center">
    <h4 class="comment_header">
        Spread the word! <%= social_share_button_tag(@post.title) %>
    </h4>
    </div>
  </div>
</div>

<div class="container-fluid">
    <div class="row">
      <div class="col-md-8 col-lg-8">
        <p class="post_content">
          <%= @post.content.html_safe %>
        </p>
      </div>
      <div class="col-md-4 col-lg-4">
        <div class="blog-sidebar">
          <%= link_to image_tag("sidebar_mini.png", :alt => "sidebar_minicourse", :class => "mini_course_sidebar"), "/course" %>
          <%= link_to image_tag("signup.png", :alt => "signup", :class => "mini_course_sidebar"), "mailto:jkent2910@gmail.com" %>
        </div>
      </div>
     </div>
  <div class="row">

    <div class="col-md-4-offset-6 col-lg-4-offset-6 text-center">
    <h4 class="comment_header">
        Spread the word! <%= social_share_button_tag(@post.title) %>
    </h4>
      
          <h5 class="small_heading">Get my FREE list of the 20 best financial resources that can help you build your wealth!</h5> 
<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{
  background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif;  width:350px; text-align: center;   margin-left: auto ;
  margin-right: auto; 
  }
  
#mc_embed_signup input.email {
  margin-left: 80px;
}
  
  #mc_embed_signup input.button {
    margin-left: 115px;
  }
  
@media only screen and (max-width: 750px) {
  
  #mc_embed_signup input.email{
    
    margin-left: 10px;
    
  }
  
    #mc_embed_signup input.button {
    margin-left: 50px;
  }
  
  
  
  
}
  
  
  
  
  
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//happyhealthywealthy.us10.list-manage.com/subscribe/post?u=f99a8de8f49f7e3b52c765fec&amp;id=8b070251e4" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_f99a8de8f49f7e3b52c765fec_8b070251e4" tabindex="-1" value=""></div>
    <input type="submit" value="Yes, send it!" name="subscribe" id="mc-embedded-subscribe" class="button">
    </div>
</form>
</div>
<!--End mc_embed_signup-->
<!--- not working      <h5 class="small_heading">You may also enjoy reading</h5>


          <h4 class="comment_header">

<% @post.categories.each do |category| %>
  <%= render partial: "/categories/categories", locals: { category: category } %>
<% end %>
            

          </h4>
      
    </div>

  </div>

        
        --->

</div>
<!---- not working yet 
<div class="container-fluid">
    <div class="row">
    <h4 class="comment_header"><%= link_to "Add a rating", new_post_rating_path(@post) %></h4><br />
</div>  ------>

 <!--- not working yet         <% if @ratings.blank? %>
          <h3>No ratings just yet, would you like to add the first!</h3>
              <%= link_to "Rate this article", new_post_rating_path(@post), class: "btn btn-danger" %>
        <% else %>
          <% @ratings.each do |rating| %>
            <div class="ratings">
              <div class="star-rating" data-score= <%= rating.rating_number %> ></div>
            </div>
          <% end %>
        <% end %>  ------>


<div class="container-fluid comments">
    <div class="row">
      <div class="col-md-4 col-lg-4">
         <h4 class="comment_header">Comments</h4>
        <p class="p_normal"> <%= @post.comments.count %> Comments</p>
            <div class="comment-wrapper">
              <% @comments.each do |comment| %>
                <p class="p_heading">Name:<p/>  <p class="p_normal"><%= comment.name %></p>
                <p class="p_heading">Comment:</p> 
                <p class="p_normal"><%= comment.body %></p>
              <% end %>
            </div>
    </div>
      
</div>

  <div class="container-fluid">
  <div class="row">
    <h4 class="comment_header"><%= link_to "Add a comment", new_post_comment_path(@post) %></h4><br />
    <% if current_admin != Post.friendly.find(params[:id]).admin %>
      <%= link_to "Back", posts_path, class: "btn btn-primary" %>
    <% else %>
      <%= link_to "Back", posts_path, class: "btn btn-primary" %>
      <%= link_to "Edit", edit_post_path, class: "btn btn-default" %>
      <%= link_to "Delete", post_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default" %>
    <% end %>

    </div>
</div>


<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/ratings/_form.html.erb
<%= form_for([@post, @post.ratings.build]) do |f| %>
  <div class="field">
    <div id="star-rating"></div>
  </div>
    <%= f.submit %>
<% end %>



<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'rating[rating_number]'
  });
</script>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render 'form' %>

<%= link_to 'Back', post_path(@post) %>

app/views/ratings/new.html.erb
<h1> New rating </h1>

<%= render 'form' %>

<%= link_to 'Back', post_path(@post) %>